# Generated by Django 3.1.7 on 2021-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210508_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
    ]
